spring:
  # 环境 dev|test|pro
  profiles:
    active: dev
  application:
    name: gateway
server:
  port: 7000

#eureka
eureka:
  port: 7001
  client:
    serviceUrl:
      defaultZone: http://springwind:1q&*!sw123@localhost:${eureka.port}/eureka/

#hystrix重试超时设置
hystrix:
  command:
    default:
        execution:
            timeout:
                enabled: true
            isolation:
                thread:
                  timeoutInMilliseconds: 80000

#ribbon超时设置
ribbon:
  ReadTimeout: 80000
  ConnectTimeout: 80000
#ribbon重试
#ribbon.MaxAutoRetries=0
#ribbon.MaxAutoRetriesNextServer=1
#ribbon.eureka.enabled=false

# 允许传递请求头信息
zuul:
  sensitiveHeaders: '*'
#zuul代理超时设置
#zuul.max.host.connections=500

